### ISSUE TITLE
Battery level notification icon broken after wake

### ISSUE THREAD

**Issue by marcinjahn** [elementary/notifications#138] opened 2021-03-18 16:20 UTC
As mentioned in another issue, I am getting lots of mouse battery level notifications. One time, after logging into the PC (I think it was in sleep mode before, but I'm not sure), I saw this:

![battery bug](https://user-images.githubusercontent.com/10273406/111660195-206f0b00-880e-11eb-822c-719627f4200a.png)

Normally, the notification should look like this:

![battery ok](https://user-images.githubusercontent.com/10273406/111660237-295fdc80-880e-11eb-82e1-6ab8d5b0983e.png)

It seems that the animation that would normally be displayed got stuck somehow.

**Comment by danrabbit** [comment] 2021-06-30 16:50
I'm going to transfer this issue to the notification server since it seems this is related to the animation in the notification.

It does appear that this issue occured in the old gala-based notification server and not the new GTK one, so I'm going to mark as "incomplete" until we can get it reproduced with the new server. It may have already been fixed in the rewrite

**Comment by lenemter** [comment] 2023-07-05 09:35
Closing because the report is old and the issue was in the old gala notification server.

**Closed by lenemter** 2023-07-05 09:35 UTC
Labels: Status: Incomplete
