### ISSUE TITLE
Character bug in notifications

### ISSUE THREAD

**Issue by xKesvaL** [elementary/notifications#84] opened 2020-07-13 22:57 UTC
Not a big problem but,
when i get a notification containing certain characters, the notification is messed up.
This is what i mean \:
![Screenshot from 2020-07-14 00-53-35](https://user-images.githubusercontent.com/47763141/87361501-a692cd80-c56c-11ea-8e8e-4eb8183f329b.png)
This character is a simple quote ', so it's used frequently.

I would like to see this fixed, thanks!

**Comment by Brin-o** [comment] 2021-05-26 12:53
I can confirm this happens to me as well on elementary OS 5.1.7 Hera

**Comment by andirsun** [comment] 2021-06-13 07:07
I think is solved in elementary os odin couse Im not able to reproduce it
![Screenshot from 2021-06-13 02-05-10](https://user-images.githubusercontent.com/22928302/121798427-e8e4e480-cbeb-11eb-912b-37269c3515ec.png).
Please @xKesvaL could you check it out.

**Comment by danrabbit** [comment] 2021-06-14 16:35
I believe this is indeed fixed in the new notifications server

**Closed by danrabbit** 2021-06-14 16:35 UTC
