### ISSUE TITLE
Bluetooth automatically turns on after waking the laptop from sleep.

### ISSUE THREAD

**Issue by 07Excel** [elementary/notifications#134] opened 2021-06-12 07:02 UTC

**Comment by jeremypw** [comment] 2021-06-12 15:49
I think this is effectively a duplicate of https://github.com/elementary/wingpanel-indicator-bluetooth/issues/142 and https://github.com/elementary/switchboard-plug-bluetooth/issues/174 there is a PR that may fix it awaiting approval here https://github.com/elementary/wingpanel-indicator-bluetooth/pull/156

**Closed** 2021-06-14 16:44 UTC
Labels: Status: Duplicate
